<a href="https://colab.research.google.com/github/Sajjad-Mahmoudi/Thesis/blob/main/Weighted_Categorical_CrossEntropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow.keras.backend as K
import tensorflow as tf

In [ ]:
y_pred = np.array([[[0.6,0.4],[0.3,0.7],[0.1,0.9],[0.23,0.77]],
                 [[0.3,0.7],[0.21,0.79],[0.99,0.01],[0.23,0.77]], 
                 [[0.1,0.9],[0.88,0.12],[0.33,0.67],[0.11,0.89]]])
y_true = np.array([[[1,0],[1,0],[0,1],[0,1]], 
                 [[0,1],[0,1],[1,0],[1,0]], 
                 [[0,1],[1,0],[1,0],[0,1]]])

In [ ]:
y_true_t = tf.constant(y_true)
y_pred_t = tf.constant(y_pred)

In [ ]:
def weighted_categorical_crossentropy(weights):
    def wcce(y_true, y_pred):
        tensor_weight = K.constant(weights, dtype=tf.float64)
        y_true = K.cast(y_true, y_pred.dtype)
        return K.categorical_crossentropy(y_true, y_pred) * K.sum(y_true * tensor_weight, axis=-1)
    return wcce

In [ ]:
tensor_weight = K.constant([0.6, 0.4], dtype=tf.float64)
y_true = K.cast(y_true, y_pred.dtype)

In [ ]:
K.categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.51082562, 1.2039728 , 0.10536052, 0.26136476],
       [0.35667494, 0.23572233, 0.01005034, 1.46967597],
       [0.10536052, 0.12783337, 1.10866262, 0.11653382]])>

In [ ]:
y_true * tensor_weight

<tf.Tensor: shape=(3, 4, 2), dtype=float64, numpy=
array([[[0.6, 0. ],
        [0.6, 0. ],
        [0. , 0.4],
        [0. , 0.4]],

       [[0. , 0.4],
        [0. , 0.4],
        [0.6, 0. ],
        [0.6, 0. ]],

       [[0. , 0.4],
        [0.6, 0. ],
        [0.6, 0. ],
        [0. , 0.4]]])>

In [ ]:
K.sum(y_true * tensor_weight, axis=-1)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.6, 0.6, 0.4, 0.4],
       [0.4, 0.4, 0.6, 0.6],
       [0.4, 0.6, 0.6, 0.4]])>

In [ ]:
K.categorical_crossentropy(y_true_t, y_pred_t) * K.sum(y_true * tensor_weight, axis=-1)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.30649537, 0.72238368, 0.04214421, 0.10454591],
       [0.14266998, 0.09428893, 0.0060302 , 0.88180558],
       [0.04214421, 0.07670002, 0.66519757, 0.04661353]])>